-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSimpleLayout/TextKitSimpleLayout/PathImageView.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 12:27:42 +0000



-- Objective C interface: @interface PathImageView
local PathImageView = objc.classInterface ("PathImageView") --[[ @inherits UIView]]

function PathImageView:initWithFrame_shape_image (frame --[[@type struct.CGRect]], shape --[[@type objc.UIBezierPath]], image --[[@type objc.UIImage]])  --[[@return objcid]] end
PathImageView.viewShape --[[@type objc.UIBezierPath]] = nil
PathImageView.viewImage --[[@type objc.UIImage]] = nil
function PathImageView:viewShape ()  --[[@return objc.UIBezierPath]] end
function PathImageView:setViewShape (viewShape --[[@type objc.UIBezierPath]])  --[[@return nil]] end
function PathImageView:viewImage ()  --[[@return objc.UIImage]] end
function PathImageView:setViewImage (viewImage --[[@type objc.UIImage]])  --[[@return nil]] end