-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSimpleLayout/TextKitSimpleLayout/ViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:21:10 +0000



-- Objective C interface: @interface ViewController
local ViewController = objc.classInterface ("ViewController") --[[ @inherits UIViewController]]

ViewController.firstColumnSizeSlider --[[@type objc.UISlider]] = nil
ViewController.column1View --[[@type objc.UIView]] = nil
ViewController.column2View --[[@type objc.UIView]] = nil
ViewController.panImageView --[[@type objc.PathImageView]] = nil
function ViewController:firstColumnSizeSlider ()  --[[@return objc.UISlider]] end
function ViewController:setFirstColumnSizeSlider (firstColumnSizeSlider --[[@type objc.UISlider]])  --[[@return nil]] end
function ViewController:column1View ()  --[[@return objc.UIView]] end
function ViewController:setColumn1View (column1View --[[@type objc.UIView]])  --[[@return nil]] end
function ViewController:column2View ()  --[[@return objc.UIView]] end
function ViewController:setColumn2View (column2View --[[@type objc.UIView]])  --[[@return nil]] end
function ViewController:panImageView ()  --[[@return objc.PathImageView]] end
function ViewController:setPanImageView (panImageView --[[@type objc.PathImageView]])  --[[@return nil]] end