// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSimpleLayout/TextKitSimpleLayout/PathImageView.h
// Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:21:09 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "PathImageView.h"

// Register Objective C methods extended signatures

@implementation PathImageView (LuaModule_TextKitSimpleLayout_PathImageView)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(initWithFrame:shape:image:), "@64@0:8{CGRect={CGPoint=dd}{CGSize=dd}}16@\"UIBezierPath\"48@\"UIImage\"56" },
        { @selector(viewShape), "@\"UIBezierPath\"16@0:8" },
        { @selector(setViewShape:), "v24@0:8@\"UIBezierPath\"16" },
        { @selector(viewImage), "@\"UIImage\"16@0:8" },
        { @selector(setViewImage:), "v24@0:8@\"UIImage\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:5 forClass:[PathImageView class]];
}

@end

