// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/TextKitSimpleLayout/TextKitSimpleLayout/ViewController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:21:10 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "ViewController.h"

// Register Objective C methods extended signatures

@implementation ViewController (LuaModule_TextKitSimpleLayout_ViewController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(firstColumnSizeSlider), "@\"UISlider\"16@0:8" },
        { @selector(setFirstColumnSizeSlider:), "v24@0:8@\"UISlider\"16" },
        { @selector(column1View), "@\"UIView\"16@0:8" },
        { @selector(setColumn1View:), "v24@0:8@\"UIView\"16" },
        { @selector(column2View), "@\"UIView\"16@0:8" },
        { @selector(setColumn2View:), "v24@0:8@\"UIView\"16" },
        { @selector(panImageView), "@\"PathImageView\"16@0:8" },
        { @selector(setPanImageView:), "v24@0:8@\"PathImageView\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:8 forClass:[ViewController class]];
}

@end

